name: Publish Package to npmjs
on:
    release:
        types: [published]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: "@MinDBreaK"
            - run: npm install
            - run: npm run package
            - run: npm publish --provenance --access public
              working-directory: build/package
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
